// <auto-generated />
using System;
using BeautyClub2026App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyClub2026App.Migrations
{
    [DbContext(typeof(BeautyClubDbContext))]
    [Migration("20260521122859_InitialWithSeed")]
    partial class InitialWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BeautyClub2026App.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EntregaExpressa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            DataCadastro = new DateTime(2026, 5, 6, 9, 28, 59, 254, DateTimeKind.Local).AddTicks(391),
                            Descricao = "Sérum antioxidante de alta potência que ilumina, uniformiza o tom da pele e reduz linhas finas.",
                            EntregaExpressa = true,
                            ImagemUrl = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop&q=80",
                            Nome = "Sérum Facial Vitamina C 15%",
                            Preco = 149.90000000000001
                        },
                        new
                        {
                            ProdutoId = 2,
                            DataCadastro = new DateTime(2026, 4, 21, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4442),
                            Descricao = "Hidratação profunda com ácido hialurônico e ceramidas para restaurar a barreira da pele durante o sono.",
                            EntregaExpressa = false,
                            ImagemUrl = "https://images.unsplash.com/photo-1629198688000-71f23e745b6e?w=500&h=500&fit=crop&q=80",
                            Nome = "Creme Hidratante Noturno Reparador",
                            Preco = 129.5
                        },
                        new
                        {
                            ProdutoId = 3,
                            DataCadastro = new DateTime(2026, 5, 11, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4458),
                            Descricao = "Alta proteção UVA/UVB com textura invisível e controle de oleosidade por até 12 horas.",
                            EntregaExpressa = true,
                            ImagemUrl = "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop&q=80",
                            Nome = "Protetor Solar FPS 50 Toque Seco",
                            Preco = 89.900000000000006
                        },
                        new
                        {
                            ProdutoId = 4,
                            DataCadastro = new DateTime(2026, 5, 16, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4460),
                            Descricao = "Cobertura média a alta, vegana e de longa duração. Não craquela e resiste ao suor.",
                            EntregaExpressa = true,
                            ImagemUrl = "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=500&h=500&fit=crop&q=80",
                            Nome = "Base Líquida Matte Acabamento Natural",
                            Preco = 115.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            DataCadastro = new DateTime(2026, 4, 6, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4462),
                            Descricao = "Fórmula enriquecida com óleo de rícino para cílios mais volumosos, longos e saudáveis.",
                            EntregaExpressa = false,
                            ImagemUrl = "https://images.unsplash.com/photo-1631214500115-598fc2cb8d2d?w=500&h=500&fit=crop&q=80",
                            Nome = "Máscara de Cílios Volume Extremo",
                            Preco = 65.900000000000006
                        },
                        new
                        {
                            ProdutoId = 6,
                            DataCadastro = new DateTime(2026, 5, 19, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4463),
                            Descricao = "Cor intensa com acabamento acetinado. Enriquecido com manteiga de karité.",
                            EntregaExpressa = true,
                            ImagemUrl = "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500&h=500&fit=crop&q=80",
                            Nome = "Batom Hidratante Vermelho Clássico",
                            Preco = 54.899999999999999
                        },
                        new
                        {
                            ProdutoId = 7,
                            DataCadastro = new DateTime(2026, 5, 1, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4465),
                            Descricao = "Equilibra o pH da pele, acalma vermelhidões e prepara o rosto para a hidratação. Sem álcool.",
                            EntregaExpressa = false,
                            ImagemUrl = "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500&h=500&fit=crop&q=80",
                            Nome = "Tônico Facial Calmante de Camomila",
                            Preco = 72.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            DataCadastro = new DateTime(2026, 5, 13, 9, 28, 59, 255, DateTimeKind.Local).AddTicks(4466),
                            Descricao = "Reduz o frizz, sela as pontas duplas e proporciona brilho intenso sem pesar os fios.",
                            EntregaExpressa = true,
                            ImagemUrl = "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&h=500&fit=crop&q=80",
                            Nome = "Óleo Capilar Nutritivo Argan & Ojon",
                            Preco = 85.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
